apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: wazuh
  labels:
    app: wazuh-elasticsearch
spec:
  selector:
    app: wazuh-elasticsearch
  ports:
    - name: es-rest
      port: 9200
      targetPort: 9200
