apiVersion: v1
kind: Service
metadata:
  name: wazuh-elasticsearch
  namespace: wazuh
  labels:
    app: wazuh-elasticsearch
spec:
  selector:
    app: wazuh-elasticsearch
  ports:
    - name: es-nodes
      port: 9300
      targetPort: 9300
  clusterIP: None
