apiVersion: v1
data:
  config.yaml: |
    insecure_server: true
    grpc_insecure: true

    authenticate_service_url: https://authenticate.your-domain.com
    authorize_service_url: https://pomerium-authorize-service.pomerium.svc.cluster.local
    cache_service_url: https://pomerium-cache-service.pomerium.svc.cluster.local

    override_certificate_name: "*.your-domain.com"

    idp_provider: google
    idp_client_id: [REPLACEME]
    idp_client_secret: [REPLACEME]

    policy:
      - from: https://httpbin.your-domain.com
        to: http://httpbin.pomerium.svc.cluster.local:8000
        allowed_domains:
          - your-domain.com
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
