apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kamus-sample-app
  labels:
    app: kamus-sample-app
spec:
  template:
    metadata:
      labels:
        app: kamus-sample-app
    spec:
      serviceAccountName: kamus-sa
      automountServiceAccountToken: true
      initContainers:
        - name: "kamus-init"
          image: "soluto/kamus-init-container:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: KAMUS_URL
              value: http://kamus-decryptor.default.svc.cluster.local/ 
          volumeMounts:
          - name: encrypted-secrets
            mountPath: /encrypted-secrets
          - name: decrypted-secrets
            mountPath: /decrypted-secrets
          args: ["-e","/encrypted-secrets","-d","/decrypted-secrets", "-n", "config.json"]
      containers:
        - name: app
          image: alpine:latest
          command: ["sleep", "300"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: decrypted-secrets
            mountPath: /secrets
      volumes:
        - name: encrypted-secrets
          configMap: 
            name: encrypted-secrets
        - name: decrypted-secrets
          emptyDir:
            medium: Memory
