apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: wazuh
  labels:
    app: wazuh-kibana
spec:
  selector:
    app: wazuh-kibana
  ports:
    - name: kibana
      port: 5601
      targetPort: 5601
